#!/bin/bash

ds() {
  date --date="$1 days ago" +%Y-%m-%d
}

BRANCH=master # your branch here

echo "Date,LinesAdded,LinesDeleted"
for day in $(seq 1 10)
do
  lines=$(git --no-pager log --after=$(ds $day) --before=$(ds $(($day - 1))) --format=format: --numstat $BRANCH  | awk '/([0-9]+).*([0-9]+).*/{s+=$1; t+=$2} END {printf "+"; printf s;printf ",-"; printf t;}')
  if [[ "$lines" != "+,-" ]]; then
      echo "$(ds $day),$lines"
  else
      echo "$(ds $day),0,0"
  fi
done
