---
# - name: test
  # shell: echo {{php_version}}
- name: install php{{php_version}} and extensions
  apt:
    name:  "{{ item }}"
    state: present
  with_items:
    - composer
    - php{{php_version}}
    - php{{php_version}}-mbstring
    - php{{php_version}}-xml
    - php{{php_version}}-zip
    - php{{php_version}}-fpm

